# Generated by Django 5.0.4 on 2024-04-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='blood',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student_info',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student_info',
            name='detail',
            field=models.CharField(blank=True, max_length=230),
        ),
        migrations.AddField(
            model_name='student_info',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/%y'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
