# Generated by Django 5.0.4 on 2024-04-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='bg_image',
        ),
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/%y'),
        ),
    ]
