# Generated by Django 5.0.2 on 2024-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_student_info_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='contact',
        ),
        migrations.AddField(
            model_name='student_info',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student_info',
            name='facebook',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='student_info',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
