# Generated by Django 5.0.4 on 2024-04-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_student_info_contact_student_info_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=440)),
                ('facebook', models.TextField(blank=True, max_length=440)),
            ],
        ),
    ]
