# Generated by Django 5.0.4 on 2024-04-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_blood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='blood_group',
            field=models.CharField(max_length=20),
        ),
    ]
