# Generated by Django 5.0.4 on 2024-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_blood_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='alter_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
