# Generated by Django 5.0.4 on 2024-04-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_blood_alter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='alter_phone',
            field=models.CharField(blank=True, default='N/A', max_length=20),
        ),
    ]
